# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia_m',
            name='categoria',
            field=models.IntegerField(blank=True, choices=[(1, b'Reten'), (2, b'Bache'), (3, b'Accidente'), (4, b'Reparaciones'), (5, b'Evento'), (6, b'Otro')], null=True, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='denuncia_m',
            name='nivel',
            field=models.IntegerField(blank=True, choices=[(1, b'Totalmente bloqueado'), (2, b'Parcialmente bloqueado'), (3, b'Ninguno')], null=True, verbose_name='Nivel'),
        ),
    ]
